# Databricks notebook source
# Generated by py2rocket. Edit the DSL source, not this notebook.

# COMMAND ----------

# Pipeline parameters
PARAMETERS = {}
dbutils.widgets.text('P_MIN_AMOUNT', '100')
PARAMETERS['P_MIN_AMOUNT'] = dbutils.widgets.get('P_MIN_AMOUNT')
p_min_amount = PARAMETERS['P_MIN_AMOUNT']

def _render_parameters(value):
    for _name, _value in PARAMETERS.items():
        value = value.replace('{{{' + _name + '}}}', _value)
        value = value.replace('{{' + _name + '}}', _value)
    return value

PY2ROCKET_ADAPTERS = globals().get('PY2ROCKET_ADAPTERS', {})

def _run_adapter(adapter, node_name, configuration, dfs):
    implementation = PY2ROCKET_ADAPTERS.get(adapter)
    if implementation is not None:
        return implementation(spark, dfs, configuration)
    print(f'WARNING: adapter {adapter!r} for {node_name!r} is not registered; using passthrough')
    return dfs[0] if dfs else spark.range(0)

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.window import Window

# COMMAND ----------

# Node: Load_Ventas [SQLInputStep]
# Lee las ventas desde Unity Catalog
load_ventas = spark.table('main.bronze.ventas')
load_ventas = load_ventas.cache()

# COMMAND ----------

# Node: Calculate_Total [AddColumnsTransformStep]
# Calcula el importe total
calculate_total = load_ventas
calculate_total = calculate_total.withColumn('total', F.expr('quantity * unit_price'))

# COMMAND ----------

# Node: Filter_High_Value [FilterTransformStep]
# Separa ventas activas de alto importe
_condition = _render_parameters("total >= {{P_MIN_AMOUNT}} AND status = 'active'")
filter_high_value = calculate_total.filter(_condition)
filter_high_value__discarded = calculate_total.filter((~F.expr(_condition)) | F.expr(_condition).isNull())

# COMMAND ----------

# Node: Select_Result [SelectTransformStep]
# Selecciona las columnas de salida
select_result = filter_high_value.select(*['sale_id', 'customer_id', 'total', 'status'])

# COMMAND ----------

# Node: Save_Valid_Sales [DeltaOutputStep]
# Escribe ventas válidas en Unity Catalog
select_result.write.mode('overwrite').saveAsTable('main.silver.ventas_alto_valor')

# COMMAND ----------

# Node: Show_Discarded_Sales [PrintOutputStep]
# Muestra las ventas descartadas
filter_high_value__discarded.printSchema()
print('Show_Discarded_Sales', 'rows=', filter_high_value__discarded.count(), 'columns=', len(filter_high_value__discarded.columns))
display(filter_high_value__discarded)
